services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
      target: frontend
    image: hiromikoreyes/quirknotes_frontend:latest
    environment:
      - ENV=Docker
    ports:
      - "3000:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    image: hiromikoreyes/quirknotes_backend:latest
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
